name: Deploy Production
on:
  # Manual trigger
  workflow_dispatch:
  push:
    paths:
      - '*/**'
  pull_request:
    branches: [ main ]
defaults:
  run:
    shell: bash
jobs:
  deploy-branch:
    env:
      NODE_ENV: production
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Deploy
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_DISPACTH_ACCESS_TOKEN }}
          repository: trungdung22/terraform-boilerplate
          event-type: deploy
          client-payload: '{"ref": "${{ github.ref }}", "branch": "main" , "secret_name":"env-production" }'